{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2015-5145",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "djangoproject",
            "product": {
              "product_data": [
                {
                  "product_name": "django",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "1.8.0"
                      },
                      {
                        "version_value": "1.8.1"
                      },
                      {
                        "version_value": "1.8.2"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-399"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.securityfocus.com/bid/75691"
        },
        {
          "url": "http://www.securitytracker.com/id/1032820"
        },
        {
          "url": "https://security.gentoo.org/glsa/201510-06"
        },
        {
          "url": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:djangoproject:django:1.8.0",
            "cpe23Uri": "cpe:2.3:a:djangoproject:django:1.8.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:djangoproject:django:1.8.1",
            "cpe23Uri": "cpe:2.3:a:djangoproject:django:1.8.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:djangoproject:django:1.8.2",
            "cpe23Uri": "cpe:2.3:a:djangoproject:django:1.8.2:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:C)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "COMPLETE",
        "baseScore": 7.8
      },
      "severity": "HIGH",
      "exploitabilityScore": 10.0,
      "impactScore": 6.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2015-07-14T17:59Z",
  "lastModifiedDate": "2017-09-22T01:29Z"
}