{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2010-1634",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.6"
                      },
                      {
                        "version_value": "2.7"
                      },
                      {
                        "version_value": "3.1"
                      },
                      {
                        "version_value": "3.2"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-189"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue8674"
        },
        {
          "url": "http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html"
        },
        {
          "url": "http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
        },
        {
          "url": "http://secunia.com/advisories/39937"
        },
        {
          "url": "http://secunia.com/advisories/40194"
        },
        {
          "url": "http://secunia.com/advisories/42888"
        },
        {
          "url": "http://secunia.com/advisories/43068"
        },
        {
          "url": "http://secunia.com/advisories/50858"
        },
        {
          "url": "http://secunia.com/advisories/51024"
        },
        {
          "url": "http://secunia.com/advisories/51040"
        },
        {
          "url": "http://secunia.com/advisories/51087"
        },
        {
          "url": "http://support.apple.com/kb/HT5002"
        },
        {
          "url": "http://svn.python.org/view?rev=81045&view=rev"
        },
        {
          "url": "http://svn.python.org/view?rev=81079&view=rev"
        },
        {
          "url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html"
        },
        {
          "url": "http://www.securityfocus.com/bid/40370"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1596-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1613-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1613-2"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1616-1"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2010/1448"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0122"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0212"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:2.6",
            "cpe23Uri": "cpe:2.3:a:python:python:2.6:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:2.7",
            "cpe23Uri": "cpe:2.3:a:python:python:2.7:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.2",
            "cpe23Uri": "cpe:2.3:a:python:python:3.2:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-05-27T19:30Z",
  "lastModifiedDate": "2013-05-15T03:08Z"
}