{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2002-1119",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python_software_foundation",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.2.1"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "ftp://ftp.caldera.com/pub/security/OpenLinux/CSSA-2002-045.0.txt"
        },
        {
          "url": "http://distro.conectiva.com.br/atualizacoes/?id=a&anuncio=000527"
        },
        {
          "url": "http://mail.python.org/pipermail/python-dev/2002-August/027229.html"
        },
        {
          "url": "http://marc.info/?l=bugtraq&m=104333092200589&w=2"
        },
        {
          "url": "http://www.debian.org/security/2002/dsa-159"
        },
        {
          "url": "http://www.iss.net/security_center/static/10009.php"
        },
        {
          "url": "http://www.linux-mandrake.com/en/security/2002/MDKSA-2002-082.php"
        },
        {
          "url": "http://www.redhat.com/support/errata/RHSA-2002-202.html"
        },
        {
          "url": "http://www.redhat.com/support/errata/RHSA-2003-048.html"
        },
        {
          "url": "http://www.securityfocus.com/bid/5581"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "os._execvpe from os.py in Python 2.2.1 and earlier creates temporary files with predictable names, which could allow local users to execute arbitrary code via a symlink attack."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python_software_foundation:python",
            "cpe23Uri": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "2.2.1"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:L/AC:L/Au:N/C:P/I:P/A:P)",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.6
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 3.9,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": true,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2002-10-04T04:00Z",
  "lastModifiedDate": "2016-10-18T02:23Z"
}