{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2010-3494",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "g.rodola",
            "product": {
              "product_data": [
                {
                  "product_name": "pyftpdlib",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.1"
                      },
                      {
                        "version_value": "0.1.1"
                      },
                      {
                        "version_value": "0.2.0"
                      },
                      {
                        "version_value": "0.3.0"
                      },
                      {
                        "version_value": "0.4.0"
                      },
                      {
                        "version_value": "0.5.0"
                      },
                      {
                        "version_value": "0.5.1"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-362"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue6706"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=104"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=105"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/detail?r=556"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn556&r=556&format=side&path=/trunk/pyftpdlib/ftpserver.py"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
        },
        {
          "url": "https://bugs.launchpad.net/zodb/+bug/135108"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.1",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.1.1",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.2.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.3.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.4.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib:0.5.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.5.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:g.rodola:pyftpdlib",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.5.1"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:M/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.3
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-10-19T20:00Z",
  "lastModifiedDate": "2010-10-20T04:00Z"
}