{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2013-2104",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "openstack",
            "product": {
              "product_data": [
                {
                  "product_name": "python-keystoneclient",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.2.2"
                      },
                      {
                        "version_value": "0.2.3"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-264"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://lists.opensuse.org/opensuse-updates/2013-06/msg00198.html"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2013-0944.html"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2013/05/28/7"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1851-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1875-1"
        },
        {
          "url": "https://bugs.launchpad.net/python-keystoneclient/+bug/1179615"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "python-keystoneclient before 0.2.4, as used in OpenStack Keystone (Folsom), does not properly check expiry for PKI tokens, which allows remote authenticated users to (1) retain use of a token after it has expired, or (2) use a revoked token once it expires."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:openstack:python-keystoneclient:0.2.2",
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:0.2.2:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:openstack:python-keystoneclient",
            "cpe23Uri": "cpe:2.3:a:openstack:python-keystoneclient:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.2.3"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:S/C:N/I:P/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "SINGLE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.5
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.0,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2014-01-21T18:55Z",
  "lastModifiedDate": "2014-01-22T21:57Z"
}