{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2007-4643",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "doomsday",
            "product": {
              "product_data": [
                {
                  "product_name": "doomsday",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "1.9.0_beta5.1"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-119"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://aluigi.org/poc/dumsdei.zip"
        },
        {
          "url": "http://bugs.gentoo.org/show_bug.cgi?id=190835"
        },
        {
          "url": "http://secunia.com/advisories/26524"
        },
        {
          "url": "http://secunia.com/advisories/28821"
        },
        {
          "url": "http://security.gentoo.org/glsa/glsa-200802-02.xml"
        },
        {
          "url": "http://securityreason.com/securityalert/3084"
        },
        {
          "url": "http://www.securityfocus.com/archive/1/archive/1/478077/100/0/threaded"
        },
        {
          "url": "http://www.securityfocus.com/bid/25483"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/36338"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Integer underflow in Doomsday (aka deng) 1.9.0-beta5.1 and earlier allows remote attackers to cause a denial of service (daemon crash) via a PKT_CHAT packet with a data length less than 3, which triggers an erroneous malloc, possibly related to the Sv_HandlePacket function in sv_main.c."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:doomsday:doomsday",
            "cpe23Uri": "cpe:2.3:a:doomsday:doomsday:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "1.9.0_beta5.1"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2007-08-31T23:17Z",
  "lastModifiedDate": "2017-07-29T01:33Z"
}