{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2015-7298",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "digia",
            "product": {
              "product_data": [
                {
                  "product_name": "qt",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "5.3.0"
                      },
                      {
                        "version_value": "5.4.1"
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "vendor_name": "owncloud",
            "product": {
              "product_data": [
                {
                  "product_name": "owncloud_desktop_client",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.0.0"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://owncloud.org/security/advisory/?id=oc-sa-2015-016"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "ownCloud Desktop Client before 2.0.1, when compiled with a Qt release after 5.3.x, does not call QNetworkReply::ignoreSslErrors with the list of errors to be ignored, which makes it easier for remote attackers to conduct man-in-the-middle (MITM) attacks by leveraging a server using a self-signed certificate.  NOTE: this vulnerability exists because of a partial CVE-2015-4456 regression."
        },
        {
          "lang": "en",
          "value": "<a href=\"http://cwe.mitre.org/data/definitions/297.html\" target=\"_blank\">CWE-297: Improper Validation of Certificate with Host Mismatch</a>"
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:digia:qt:5.3.0",
            "cpe23Uri": "cpe:2.3:a:digia:qt:5.3.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:digia:qt:5.4.1",
            "cpe23Uri": "cpe:2.3:a:digia:qt:5.4.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:owncloud:owncloud_desktop_client",
            "cpe23Uri": "cpe:2.3:a:owncloud:owncloud_desktop_client:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "2.0.0"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:H/Au:N/C:P/I:P/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.1
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 4.9,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2015-10-26T14:59Z",
  "lastModifiedDate": "2015-10-28T11:39Z"
}